import { GoogleGenAI } from "@google/genai";
import { ImageResolution, AspectRatio } from "../types";

// Convert File to Base64
export const fileToGenerativePart = async (file: File): Promise<{ inlineData: { data: string; mimeType: string } }> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = (reader.result as string).split(',')[1];
      resolve({
        inlineData: {
          data: base64String,
          mimeType: file.type,
        },
      });
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

// 1. Analyze the uploaded image using gemini-2.5-flash
export const analyzeImageVibe = async (file: File): Promise<string> => {
  // Create instance just before calling
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const imagePart = await fileToGenerativePart(file);
  
  const prompt = `
    Analyze this image in extreme detail for the purpose of recreating the subject in a new 4K render.
    Focus on:
    1. Physical appearance (Face shape, eye color, hair style/color/texture, skin tone, body type).
    2. Clothing details (Fabric, cut, style, colors).
    3. Distinctive features.
    
    Output a concise but highly descriptive paragraph starting with "A photorealistic depiction of..."
    Do not mention the background or lighting of the original image, only the subject and their attire.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [imagePart, { text: prompt }]
      }
    });

    return response.text || "A cool person.";
  } catch (error) {
    console.error("Analysis failed", error);
    throw new Error("Failed to analyze image vibes.");
  }
};

// 2. Generate the new masterpiece using gemini-2.5-flash-image
export const manifestMasterpiece = async (
  file: File | null,
  description: string,
  angle: string,
  pose: string,
  lighting: string,
  resolution: ImageResolution,
  ratio: AspectRatio
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  // Construct the "God Prompt"
  const fullPrompt = `
    ${description}
    
    The subject is ${pose}.
    The shot is ${angle}.
    The lighting is ${lighting}.
    
    Aesthetic: 8k resolution, raw photo, hyper-realistic, highly detailed texture, cinematic lighting, masterpiece, sharp focus, shot on Hasselblad, 120mm lens.
  `;

  try {
    const parts: any[] = [{ text: fullPrompt }];
    
    // We optionally include the original image to guide identity.
    if (file) {
        const imagePart = await fileToGenerativePart(file);
        parts.unshift(imagePart);
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: parts
      },
      config: {
        imageConfig: {
            // imageSize is not supported in gemini-2.5-flash-image
            aspectRatio: ratio
        }
      }
    });

    // Extract image
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the cosmos.");
  } catch (error) {
    console.error("Manifestation failed", error);
    throw error;
  }
};